[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          forward
    Host          0.0.0.0
    Port          24224

[FILTER]
    Name          parser
    Match         *
    Key_Name      log
    Parser        json
    Reserve_Data  On

[FILTER]
    Name          lua
    Match         *
    script        /fluent-bit/etc/ecs_map.lua
    call          ecs_map

[OUTPUT]
    Name                  es
    Match                 *
    Host                  elasticsearch
    Port                  9200
    Index                 duangdee-logs
    Suppress_Type_Name    On
    Buffer_Size           5M
    Time_Key              @timestamp
    Time_Key_Format       %Y-%m-%dT%H:%M:%SZ
    Replace_Dots          Off
    Logstash_Format       Off
