-- Up Migration: Seed 78 Tarot Cards Master Data
INSERT INTO tarot_cards (id, name, arcana_type, suit, number, image_url) VALUES
(0, 'The Fool', 'major', 'pentacles', 0, '/assets/cards/m00.jpg'),
(1, 'The Magician', 'major', 'pentacles', 1, '/assets/cards/m01.jpg'),
(2, 'The High Priestess', 'major', 'pentacles', 2, '/assets/cards/m02.jpg'),
(3, 'The Empress', 'major', 'pentacles', 3, '/assets/cards/m03.jpg'),
(4, 'The Emperor', 'major', 'pentacles', 4, '/assets/cards/m04.jpg'),
(5, 'The Hierophant', 'major', 'pentacles', 5, '/assets/cards/m05.jpg'),
(6, 'The Lovers', 'major', 'pentacles', 6, '/assets/cards/m06.jpg'),
(7, 'The Chariot', 'major', 'pentacles', 7, '/assets/cards/m07.jpg'),
(8, 'Strength', 'major', 'pentacles', 8, '/assets/cards/m08.jpg'),
(9, 'The Hermit', 'major', 'pentacles', 9, '/assets/cards/m09.jpg'),
(10, 'Wheel of Fortune', 'major', 'pentacles', 10, '/assets/cards/m10.jpg'),
(11, 'Justice', 'major', 'pentacles', 11, '/assets/cards/m11.jpg'),
(12, 'The Hanged Man', 'major', 'pentacles', 12, '/assets/cards/m12.jpg'),
(13, 'Death', 'major', 'pentacles', 13, '/assets/cards/m13.jpg'),
(14, 'Temperance', 'major', 'pentacles', 14, '/assets/cards/m14.jpg'),
(15, 'The Devil', 'major', 'pentacles', 15, '/assets/cards/m15.jpg'),
(16, 'The Tower', 'major', 'pentacles', 16, '/assets/cards/m16.jpg'),
(17, 'The Star', 'major', 'pentacles', 17, '/assets/cards/m17.jpg'),
(18, 'The Moon', 'major', 'pentacles', 18, '/assets/cards/m18.jpg'),
(19, 'The Sun', 'major', 'pentacles', 19, '/assets/cards/m19.jpg'),
(20, 'Judgement', 'major', 'pentacles', 20, '/assets/cards/m20.jpg'),
(21, 'The World', 'major', 'pentacles', 21, '/assets/cards/m21.jpg'),
(22, 'Ace of Cups', 'minor', 'cups', 1, '/assets/cards/c01.jpg'),
(23, 'Two of Cups', 'minor', 'cups', 2, '/assets/cards/c02.jpg'),
(24, 'Three of Cups', 'minor', 'cups', 3, '/assets/cards/c03.jpg'),
(25, 'Four of Cups', 'minor', 'cups', 4, '/assets/cards/c04.jpg'),
(26, 'Five of Cups', 'minor', 'cups', 5, '/assets/cards/c05.jpg'),
(27, 'Six of Cups', 'minor', 'cups', 6, '/assets/cards/c06.jpg'),
(28, 'Seven of Cups', 'minor', 'cups', 7, '/assets/cards/c07.jpg'),
(29, 'Eight of Cups', 'minor', 'cups', 8, '/assets/cards/c08.jpg'),
(30, 'Nine of Cups', 'minor', 'cups', 9, '/assets/cards/c09.jpg'),
(31, 'Ten of Cups', 'minor', 'cups', 10, '/assets/cards/c10.jpg'),
(32, 'Page of Cups', 'minor', 'cups', 11, '/assets/cards/c11.jpg'),
(33, 'Knight of Cups', 'minor', 'cups', 12, '/assets/cards/c12.jpg'),
(34, 'Queen of Cups', 'minor', 'cups', 13, '/assets/cards/c13.jpg'),
(35, 'King of Cups', 'minor', 'cups', 14, '/assets/cards/c14.jpg'),
(36, 'Ace of Swords', 'minor', 'swords', 1, '/assets/cards/s01.jpg'),
(37, 'Two of Swords', 'minor', 'swords', 2, '/assets/cards/s02.jpg'),
(38, 'Three of Swords', 'minor', 'swords', 3, '/assets/cards/s03.jpg'),
(39, 'Four of Swords', 'minor', 'swords', 4, '/assets/cards/s04.jpg'),
(40, 'Five of Swords', 'minor', 'swords', 5, '/assets/cards/s05.jpg'),
(41, 'Six of Swords', 'minor', 'swords', 6, '/assets/cards/s06.jpg'),
(42, 'Seven of Swords', 'minor', 'swords', 7, '/assets/cards/s07.jpg'),
(43, 'Eight of Swords', 'minor', 'swords', 8, '/assets/cards/s08.jpg'),
(44, 'Nine of Swords', 'minor', 'swords', 9, '/assets/cards/s09.jpg'),
(45, 'Ten of Swords', 'minor', 'swords', 10, '/assets/cards/s10.jpg'),
(46, 'Page of Swords', 'minor', 'swords', 11, '/assets/cards/s11.jpg'),
(47, 'Knight of Swords', 'minor', 'swords', 12, '/assets/cards/s12.jpg'),
(48, 'Queen of Swords', 'minor', 'swords', 13, '/assets/cards/s13.jpg'),
(49, 'King of Swords', 'minor', 'swords', 14, '/assets/cards/s14.jpg'),
(50, 'Ace of Wands', 'minor', 'wands', 1, '/assets/cards/w01.jpg'),
(51, 'Two of Wands', 'minor', 'wands', 2, '/assets/cards/w02.jpg'),
(52, 'Three of Wands', 'minor', 'wands', 3, '/assets/cards/w03.jpg'),
(53, 'Four of Wands', 'minor', 'wands', 4, '/assets/cards/w04.jpg'),
(54, 'Five of Wands', 'minor', 'wands', 5, '/assets/cards/w05.jpg'),
(55, 'Six of Wands', 'minor', 'wands', 6, '/assets/cards/w06.jpg'),
(56, 'Seven of Wands', 'minor', 'wands', 7, '/assets/cards/w07.jpg'),
(57, 'Eight of Wands', 'minor', 'wands', 8, '/assets/cards/w08.jpg'),
(58, 'Nine of Wands', 'minor', 'wands', 9, '/assets/cards/w09.jpg'),
(59, 'Ten of Wands', 'minor', 'wands', 10, '/assets/cards/w10.jpg'),
(60, 'Page of Wands', 'minor', 'wands', 11, '/assets/cards/w11.jpg'),
(61, 'Knight of Wands', 'minor', 'wands', 12, '/assets/cards/w12.jpg'),
(62, 'Queen of Wands', 'minor', 'wands', 13, '/assets/cards/w13.jpg'),
(63, 'King of Wands', 'minor', 'wands', 14, '/assets/cards/w14.jpg'),
(64, 'Ace of Pentacles', 'minor', 'pentacles', 1, '/assets/cards/p01.jpg'),
(65, 'Two of Pentacles', 'minor', 'pentacles', 2, '/assets/cards/p02.jpg'),
(66, 'Three of Pentacles', 'minor', 'pentacles', 3, '/assets/cards/p03.jpg'),
(67, 'Four of Pentacles', 'minor', 'pentacles', 4, '/assets/cards/p04.jpg'),
(68, 'Five of Pentacles', 'minor', 'pentacles', 5, '/assets/cards/p05.jpg'),
(69, 'Six of Pentacles', 'minor', 'pentacles', 6, '/assets/cards/p06.jpg'),
(70, 'Seven of Pentacles', 'minor', 'pentacles', 7, '/assets/cards/p07.jpg'),
(71, 'Eight of Pentacles', 'minor', 'pentacles', 8, '/assets/cards/p08.jpg'),
(72, 'Nine of Pentacles', 'minor', 'pentacles', 9, '/assets/cards/p09.jpg'),
(73, 'Ten of Pentacles', 'minor', 'pentacles', 10, '/assets/cards/p10.jpg'),
(74, 'Page of Pentacles', 'minor', 'pentacles', 11, '/assets/cards/p11.jpg'),
(75, 'Knight of Pentacles', 'minor', 'pentacles', 12, '/assets/cards/p12.jpg'),
(76, 'Queen of Pentacles', 'minor', 'pentacles', 13, '/assets/cards/p13.jpg'),
(77, 'King of Pentacles', 'minor', 'pentacles', 14, '/assets/cards/p14.jpg')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  arcana_type = EXCLUDED.arcana_type,
  suit = EXCLUDED.suit,
  number = EXCLUDED.number,
  image_url = EXCLUDED.image_url;
